### ISSUE TITLE
1.12 No Rocky or Marble Hive Worldgen

### ISSUE THREAD

**Issue by Tauchy** [ForestryMC/Binnie#274]
unstable 1.12 pack
binnie-mods-1.12-2.3.0.32
forestry_1.12-5.5.0.169
forge 2443

No Rocky or Marble Hives spawn anywhere in the world (or any other dimension). Water and Nether Hives spawn ok.

If you cheat in the Rocky and Marble Hive and place them they are named Water Hive, maybe that is causing the issiue?

**Comment by p-schneider** [comment]
I just discovered the bug (missing rocky hives) myself today. After looking around in the source code I found this Issue already reported just 4 hours ago. The bug however must have been around for quite some time. (since may for rocky bees?)
I just proposed a fix (PR) in #277

**Comment by p-schneider** [comment]
The rocky hive generation is bugged so currently rocky hives can never spawn.

Marble Hives never spawn **if there is no Marble block** (oredict stoneMarble) in your modpack. (Vanilla Minecraft, Forestry or Binnie don't add any Marble block.)
If you have a mod like [Chisel](https://minecraft.curseforge.com/projects/chisel) installed Marble Hives should generate, but way less frequent than rocky hives.
So with marble generation it is more like a balance issue to adjust where to generate those hives.

**Comment by Tauchy** [comment]
Yes Chisel is installed and i've not seen a single marble Hive, i'll try upping the spawn rate and try again in a test world.

**Comment by p-schneider** [comment]
If you know how to compile the mod yourself you can test it by adding the line `System.err.println("Generating Marble Hive at " + position.toString());` before or after [line 45 in extrabees/src/main/java/binnie/extrabees/worldgen/WorldGenHiveMarble.java](https://github.com/ForestryMC/Binnie/blob/master-MC1.12/extrabees/src/main/java/binnie/extrabees/worldgen/WorldGenHiveMarble.java#L45)
Then you can watch your log while generating new terrain for the position of marble hives.
I sometimes use the Mekanism Digital Miner to "find" hives. (Silk Touch mode using hive from nei/jei for the filter.)

To compile just download .zip or git clone the repo and run `gradlew.bat setupDevWorkspace build` (windows) or `./gradlew setupDevWorkspace build` (linux etc.) from the command line and copy the generated output from build/libs/binnie-mods-1.12-2.3.0.jar to your mods folder.

**Comment by HammerDave** [comment]
This issue is also present in 1.11.2

**Comment by mezz** [comment]
The fix has been pushed to 1.11.2 and 1.12 now.

**Comment by Robijnvogel** [comment]
@mezz just as a heads-up I have been playing on DW 1.12.2 for a while now and I have neither found any Marble Hives in the world and they don't show as generating in the world in JEI (JEIBees and JEIIntegration) either.
The pack has both Chisel (which does register its Marble that is generated as stoneMarble, by the way_ and the Twilight Forest.

Do Marble Hives generate anywhere at all at the moment?

**Comment by Boomflex** [comment]
Seeing this in:

FTB Revelations v2.0.0 also.

Binnie's Mods: v1.12.2-2.5.0.165

Extrabees main.conf reads

Sets the worldgen spawn chance for marble hives. [range: 0 ~ 10, default: 2]
    I:marbleHiveRate=2

**Comment by Nedelosk** [comment]
This should be fixed after #486.

**Comment by LemADEC** [comment]
https://github.com/ForestryMC/Binnie/pull/580 was merged but players are still unable to find Marble hives as of binnie-mods-1.12.2-2.5.1.188.jar + forestry_1.12.2-5.8.2.387.jar.
We do have stoneMarble entries from AstralSorcery, Chisel, ProjectRed and Quark.

**Comment by v1993** [comment]
This is still very much broken, sadly. No marble bees with ProjectRed marble (properly oredicted) and `S:marbleHiveRate=10.0`. Rocky bees spawn perfectly fine.

**Comment by xJon** [comment]
This is still an issue with the marble hives.

**Comment by ACGaming** [comment]
Spawning conditions for marble hives are extremely specific, locations are only valid if they are next to marble and have _exactly one_ side of the hive block facing another block (or air) that isn‘t marble. This causes these hives to be extremely rare, even though spawning itself works just fine technically.
Allowing them to face one _or more_ blocks bumps up the generation rate by a multiple already while still being balanced enough from what I could tell during my play testing.
