### ISSUE TITLE
Exception ticking world causing server crash.

### ISSUE THREAD

**Issue by tezukitty** [ForestryMC/Binnie#637]
This issue was marked as a duplicate and closed multiple times by Nedelosk (in #636 , #626 , and #628 ) with nothing being done about it, despite it causing crashes on 1.12.2 servers. Clearly this is still an issue as of March 18.

Here is the error report 
`Time: 3/18/20 10:20 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at forestry.arboriculture.genetics.TreeGrowthHelper.hasSufficientSaplingsAroundSapling(TreeGrowthHelper.java:65)
	at forestry.arboriculture.genetics.TreeGrowthHelper.canGrow(TreeGrowthHelper.java:20)
	at forestry.arboriculture.genetics.Tree.canGrow(Tree.java:167)
	at binnie.extratrees.gen.BinnieWorldGenTree.canGrow(BinnieWorldGenTree.java:62)
	at binnie.extratrees.gen.BinnieWorldGenTree.generate(BinnieWorldGenTree.java:115)
	at forestry.arboriculture.tiles.TileSapling.tryGrow(TileSapling.java:99)
	at forestry.arboriculture.tiles.TileSapling.onBlockTick(TileSapling.java:50)
	at forestry.arboriculture.blocks.BlockTreeContainer.func_180650_b(BlockTreeContainer.java:44)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)`

and here is the stacktrace.
`Stacktrace:
	at forestry.arboriculture.genetics.TreeGrowthHelper.hasSufficientSaplingsAroundSapling(TreeGrowthHelper.java:65)
	at forestry.arboriculture.genetics.TreeGrowthHelper.canGrow(TreeGrowthHelper.java:20)
	at forestry.arboriculture.genetics.Tree.canGrow(Tree.java:167)
	at binnie.extratrees.gen.BinnieWorldGenTree.canGrow(BinnieWorldGenTree.java:62)
	at binnie.extratrees.gen.BinnieWorldGenTree.generate(BinnieWorldGenTree.java:115)
	at forestry.arboriculture.tiles.TileSapling.tryGrow(TileSapling.java:99)
	at forestry.arboriculture.tiles.TileSapling.onBlockTick(TileSapling.java:50)
	at forestry.arboriculture.blocks.BlockTreeContainer.func_180650_b(BlockTreeContainer.java:44)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
`

**Comment by Nedelosk** [comment]
I am sorry about my closing. I fixed it internally but it seems like I forgot to push the fix to Github.

**Comment by Nedelosk** [comment]
This should now be fixed. It would be great if you could test it and give me feedback.

**Comment by Rihadist** [comment]
I am still having this issue. My server is crashing after a few minutes of playing with an almost identical error log, but different numbers which I am assuming means different tree IDs. I have updated forestry and Binnie mods to the latest versions is there anything else I need to do?

Crash log: https://pastebin.com/Tg2F8i2q

**Comment by nstearns96** [comment]
@Nedelosk I'm still getting this as well, but I have a fix for it. Pull request should be up sometime today.

**Comment by Rihadist** [comment]
@Nedelosk @nstearns96 
Unfortunately, after a bit of testing, it seems that I got the same crash log again. I updated my Binnie mods (202) and forestry (418) I was able to play for about an hour before the server crashed. Before this fix, I was only able to stay on for around 5 minutes before a crash occurred. 

Crash log: https://pastebin.com/dU5aN2my

**Comment by nstearns96** [comment]
Can you tell me anything about the saplings? did you place them yourself? are they naturally generated (meaning you didn't place any but you're crashing) etc

**Comment by nstearns96** [comment]
Nvm, I've found the bug

**Comment by Rihadist** [comment]
Thanks for replying so quickly. Hopefully this works!
